### ISSUE TITLE
Can't send message without image on iPadOS and iOS

### ISSUE THREAD

**Issue by Pacifiquateure** [021-projects/real-time-chat#1]
Hi,
On iPadOS or iOS version 16 +, it is impossible to send a message without it forcing us to send an image.

https://github.com/021-projects/real-time-chat/assets/34781128/64380a6e-982a-4131-be7b-f1894dceddb3

**Comment by 021-projects** [comment]
Hello,

Does the issue exist on the default XenForo style?

**Comment by Pacifiquateure** [comment]
Hi,
I just tested on the default style and everything works fine. It's on UI.X styles where it doesn't work
