### ISSUE TITLE
Compatibility with Style Switch addon from ThemeHouse

### ISSUE THREAD

**Issue by Pacifiquateure** [021-projects/real-time-chat#2]
Hi,
When ThemeHouse's Style Switch addon is installed/enabled, the chat gets stuck on "Connecting..."

**Comment by 021-projects** [comment]
Hello,

I need access to this add-on to find out the cause.

**Comment by 021-projects** [comment]
Access to the add-on was not provided. Please open a new Issue when available to provide a copy of the add-on.
